# Generated by Django 3.1.7 on 2021-03-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('Company', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=250, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('Contact', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
